---
  - name: generate a configuration file
    shell: /usr/sbin/cjdroute --genconf | /usr/sbin/cjdroute --cleanconf > /etc/cjdroute.conf creates=/etc/cjdroute.conf
    notify:
      - restart cjdns
  - name: Add an AuthorizedPassword
    cjdns:
      authorizedPassword:
        user: "{{ item }}"
        password: "{{ lookup('password', 'AuthorizedPasswords/' + ansible_hostname + '/' + item, length=30) }}"
      state: present
    with_items: play_hosts
    when: item != inventory_hostname
  - name: Iniate peering
    cjdns:
      udppeer:
        address: "{{ hostvars[item]['ansible_default_ipv4']['address'] }}:{{ hostvars[item]['cjdns']['UDPInterface'][0]['port']}}"
        data:
          publicKey: "{{ hostvars[item]['cjdns']['public_key'] }}"
          password: "{{ lookup('password', 'AuthorizedPasswords/' + item + '/' + ansible_hostname, length=30) }}"
          hostname: "{{ hostvars[item]['ansible_hostname']}}"
          info: "Automatically added by ansible"
      state: present
    with_items: play_hosts
    when: item != inventory_hostname
